name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  WORKFLOW: workflow_dispatch
  PUSH: push

jobs:
  deploy:
#    if: env.GITHUB_EVENT_NAME == 'workflow_dispatch' || (env.GITHUB_EVENT_NAME == 'push' && github.event.pusher.name != 'github-pages' && github.event.commits[0] != null)

    name: Deploy

    runs-on: ubuntu-latest

    steps:
#      - name: Setup git repo
#        uses: actions/checkout@v3
#
#      - name: Setup Node.js
#        uses: actions/setup-node@v2
#        with:
#          node-version: '14'
#
#      - name: Install dependencies
#        run: npm ci

      - name: Set workflow dispatch deploy message
        if: ${{ env.GITHUB_EVENT_NAME == env.WORKFLOW }}
        env:
          DEPLOY_MESSAGE: Manual deploy.
        run: echo "Deploy test message - $DEPLOY_MESSAGE"
#
      - name: Set push deploy message
        if: ${{ env.GITHUB_EVENT_NAME == env.PUSH }}
        env:
          DEPLOY_MESSAGE: Automated deploy triggered by commit ${{ github.event.head_commit.id }}
        run: echo "Deploy test message - $DEPLOY_MESSAGE"
#
#      - name: Echo results
#        run: echo "$DEPLOY_MESSAGE"

#      - name: Deploy to gh-pages
#        run: npm run deploy -- -m "Automated deploy."
