name: Dictionary Update

on:
  workflow_dispatch:
  schedule:
  - cron: '7 4 2 * *' # Random time on a day as GitHub recommends picking something other than hour barriers to avoid delays.

jobs:
  update_dict:
    name: Update Dictionary

    runs-on: ubuntu-latest

    steps:
      - name: Setup git repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Download the dictionary file
        run: curl http://ftp.edrdg.org/pub/Nihongo/JMdict_e.gz --create-dirs -o src/resources/JMdict.gz

      - name: Extract dictionary file
        run: gzip -d src/resources/JMdict.gz

      - name: Install parser
        run: npm i -g jmdict-parser

      - name: Parse dictionary
        run: jmdict-parser src/resources/JMdict

      - name: Filter dictionary
        run: python scripts/dict_parser.py src/resources/JMdict.json src/resources/FilteredJMdict.json

      - name: Commit the JSON
        env:
          USER_NAME: github-actions
          USER_EMAIL: github-actions@github.com
        run: |
          git config user.name $USER_NAME
          git config user.email $USER_EMAIL
          git add src/resources/JMdict.json src/resources/FilteredJMdict.json
          git commit -m "Automated dictionary update." || echo "No dictionary changes to commit."
          git push
