name: Dictionary Update

on:
  workflow_dispatch:

jobs:
  update_dict:
    name: Update Dictionary

    runs-on: ubuntu-latest

    steps:
      - name: Setup git repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Download the dictionary file
        run: curl http://ftp.edrdg.org/pub/Nihongo/JMdict_e.gz --create-dirs -o src/resources/JMdict.gz

      - name: Extract dictionary file
        run: gzip -d src/resources/JMdict.gz

      - name: Install parser
        run: npm i -g jmdict-parser

      - name: Parse dictionary
        run: jmdict-parser src/resources/JMdict

      - name: Commit the JSON
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add src/resources/JMdict.json
          git commit -m "Automated dictionary update."
          git push
