name: Dictionary Update

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update_dict:
    name: Update Dictionary

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Download the dictionary file
        run: wget http://ftp.edrdg.org/pub/Nihongo/JMdict_e.gz -O JMdict.xml.gz

      - name: Extract dictionary file
        run: gzip -d JMdict.xml.gz

      - uses: fabasoad/yaml-json-xml-converter-action@v1.0.0
        id: xml2json
        with:
          path: 'JMdict.xml'
          from: 'xml'
          to: 'json'

      - name: Convert to JSON
        run: echo "${{ steps.xml2json.outputs.data }}"

#      # Runs a set of commands using the runners shell
#      - name: Run a multi-line script
#        run: |
#          echo Add other actions to build,
#          echo test, and deploy your project.
